### ISSUE TITLE
Travis build speed up

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/tdlib.native#21]
Try to add this:

```yml
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup
```

Depends on #20.
